### ISSUE TITLE
Interactions are very flaky

### ISSUE THREAD

**Issue by strazto** [deekue/uebersicht-remontoire.widget#1]
I find that expanding categories is very unreliable - Maybe we could default this to auto expanding them?

**Comment by deekue** [comment]
thanks for the PR, I'm not actually using this code anymore.  I switched to using  [skhd_parse.py](https://github.com/deekue/dotfiles/blob/macos_tiling_wm/bin/skhd_parse.py) and feeding it's output to Chrome

```shell
open -na "Google Chrome" --args --new-window --app="$(skhd_parse.py -f data)"
```
